### PR TITLE
Speed up CI 

### PR DESCRIPTION
**Pull request by pitmonticone**

### CODE REVIEW

**Comment by pitmonticone** [comment]
@fpvandoorn Ready to merge

**Comment by fpvandoorn** [comment]
All of Mathlib is actually imported in a few files. Do you know why the test doesn't fail? 
Please remove that test, I don't think that is a big issue in this repo.

**Comment by pitmonticone** [comment]
No, I've never investigated that but I'll do as soon as I find the time (next few days or so).

Ok, I'm going to remove that test in a moment.

**Comment by pitmonticone** [comment]
@fpvandoorn Done.

**Pull request merged**
